version: "3"
services:
  oreoreca:
    container_name: oreoreca
    build:
      context: .
      args:
        VARIANT: "3.15"
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/workspace:cached
    command:
      /bin/sh -c "while sleep 1000; do :; done"
